name: Build pyodbc_package for All Platforms

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build pyodbc_package Wheels
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Pull manylinux2014 Docker Image
        run: docker pull quay.io/pypa/manylinux2014_x86_64

      - name: Build pyodbc_package Wheel
        run: |
          docker run --rm -v $(pwd):/io quay.io/pypa/manylinux2014_x86_64 /bin/bash -c "
            yum install -y unixODBC unixODBC-devel && \
            curl https://packages.microsoft.com/keys/microsoft.asc | tee /etc/pki/rpm-gpg/MICROSOFT.asc && \
            curl https://packages.microsoft.com/config/rhel/7/prod.repo | tee /etc/yum.repos.d/mssql-release.repo && \
            ACCEPT_EULA=Y yum install -y msodbcsql17 && \
            cp /usr/lib64/libodbc.so /io/pyodbc_package/bin/ && \
            /opt/python/cp${{ matrix.python-version | replace('.', '') }}-cp${{ matrix.python-version | replace('.', '') }}/bin/python -m pip install --upgrade pip build && \
            cd /io && /opt/python/cp${{ matrix.python-version | replace('.', '') }}-cp${{ matrix.python-version | replace('.', '') }}/bin/python -m build --wheel --outdir /io/wheels
          "

      - name: Upload Built Wheels
        uses: actions/upload-artifact@v3
        with:
          name: linux-wheels-python-${{ matrix.python-version }}
          path: wheels/*.whl