name: Build pyodbc_package for All Platforms

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build pyodbc_package Wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            manylinux: true
        exclude:
          - os: windows-latest
            manylinux: true
          - os: macos-latest
            manylinux: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Build Dependencies (Linux)
        if: runner.os == 'Linux' && matrix.manylinux != true
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc unixodbc-dev

      - name: Install Build Dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install microsoft-odbc-driver-for-sql-server

      - name: Install Build Dependencies (macOS)
        if: runner.os == 'macos-latest'
        run: |
          brew install unixodbc

      - name: Build Wheel (Linux with manylinux)
        if: runner.os == 'Linux' && matrix.manylinux == true
        run: |
          docker run --rm -v $(pwd):/io quay.io/pypa/manylinux2014_x86_64 /bin/bash -c "
            yum install -y unixODBC unixODBC-devel && \
            curl https://packages.microsoft.com/keys/microsoft.asc | tee /etc/pki/rpm-gpg/MICROSOFT.asc && \
            curl https://packages.microsoft.com/config/rhel/7/prod.repo | tee /etc/yum.repos.d/mssql-release.repo && \
            ACCEPT_EULA=Y yum install -y msodbcsql17 && \
            python3 -m pip install build && \
            python3 -m build --wheel --outdir /io/wheels
          "

      - name: Build Wheel (Other OS)
        if: runner.os != 'Linux' || matrix.manylinux != true
        run: |
          python3 -m pip install build
          python3 -m build --wheel

      - name: Upload Wheels
        uses: actions/upload-artifact@v3
        with:
          name: pyodbc_package-wheels-${{ matrix.os }}-py3.10
          path: dist/*.whl